version: '3.7'
services:
  postgres:
    image: postgres
#    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=repairs
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
#      - ./src/main/resources/sql/create-types.sql:/docker-entrypoint-initdb.d/create-types.sql
#      - ./src/main/resources/sql/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql

