version: '3.7'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
#      - ./create-types.sql:/docker-entrypoint-initdb.d/create-types.sql
      - ./create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "53603:53603"
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: root

volumes:
  pg-dataset:
