#tomcat
server:
  port: 5555
  servlet.contextPath: /repairs

#db
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_DB_URL:localhost:5432/repairs}
    username: ${POSTGRESQL_DB_USERNAME:user}
    password: ${POSTGRESQL_DB_PASSWORD:pass}
  jpa:
    show-sql: true
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      dbc.lob.non_contextual_creation: true
    hibernate:
      ddl-auto: update
#  sql.init:
#    ddlScriptLocations: classpath*:resources/initDB.sql
#    data-locations: classpath*:database/populateDB.sql
##spring.sql.init.ddlScriptLocations=classpath*:resources/initDB.sql
##spring.sql.init.data-locations=classpath*:database/populateDB.sql

repair:
  coefficients:
    kitchenCoefficient: ${KITCHEN_KOEFFICIENT:1.7}
    toiletCoefficient: ${TOILET_KOEFFICIENT:1.7}
    multipleToiletCoefficient: ${MULTIPLE_TOILET_KOEFFICIENT:1.2}
    bathroomCoefficient: ${BATHROOM_KOEFFICIENT:1.9}
    multipleBathroomCoefficient: ${MULTIPLE_BATHROOM_KOEFFICIENT:1.7}
