#tomcat
server:
  port: ${PORT:5555}
  servlet.contextPath: /repairs

#db
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:repairs}
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:pass}
  jpa:
    show-sql: true
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      dbc.lob.non_contextual_creation: true
    hibernate:
      ddl-auto: validate
    generate-ddl: false
  flyway:
    baseline-on-migrate: true
    baseline-version: 0

#app props
price:
  ratio:
    time:
      HIGH: 2
      MIDDLE: 1.5
      LOW: 1
    skill:
      HIGH: 2
      MIDDLE: 1.5
      LOW: 1
